# Generated by Django 2.1.7 on 2019-04-10 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.SmallIntegerField(choices=[(0, 'Appartment'), (1, 'Holiday home'), (2, 'Bed and breakfast')])),
                ('short_description', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='deals_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='deals_pics')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealimages', to='deals.Deal')),
            ],
        ),
    ]
