# Generated by Django 2.1.7 on 2019-04-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='deals_pics')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_images', to='deals.Deal')),
            ],
        ),
    ]
