# Generated by Django 2.1.7 on 2019-03-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20190401_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Appartment'), (1, 'Holiday home'), (2, 'Bed and breakfast')]),
        ),
    ]
