# Generated by Django 2.1.7 on 2019-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20190401_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Refused')], null=True),
        ),
    ]
