# Generated by Django 2.1.7 on 2019-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='deals_pics'),
        ),
    ]
