# Generated by Django 2.1.7 on 2019-03-26 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resv', '0003_remove_deal_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
