# Generated by Django 2.1.7 on 2019-03-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resv', '0004_auto_20190326_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='picture',
            new_name='thumbnail',
        ),
    ]
