# Generated by Django 2.1.7 on 2019-03-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resv', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Appartment'), (1, 'Holiday home'), (2, 'Bed and breakfast')], default=3),
            preserve_default=False,
        ),
    ]
